# Homebrew formula for the Pretorin CLI standalone binary (issue #160).
#
# Generated by pretorin-ai release tooling; do not hand-edit url/version/sha256 —
# the release pipeline regenerates them from the signed SHA256SUMS at stable-release
# time. A 00000000… sha256 means this is the committed TEMPLATE for
# an unreleased version. Customer downloads are served from this public tap repo,
# which mirrors byte-identical copies of the verified/signed/notarized release assets.
#
# Idiomatic by design: installs into the Homebrew prefix only. It does NOT write
# to $HOME or ~/.pretorin. The canonical MCP pin (~/.pretorin/bin/pretorin) is
# owned by `pretorin link` — see the caveats block.
#
# macOS arm64 is provided for completeness; the PUBLIC macOS brew recommendation
# waits on M10 (final validation of the onedir Homebrew path). Linuxbrew is usable now.
# macOS = a onedir `.tar.gz` (launcher + _internal/), auto-extracted by brew;
# Linux = a single self-contained onefile binary (glibc-dynamic, GLIBC_2.30 floor).
# The install block branches per platform.
class Pretorin < Formula
  desc "Compliance automation CLI and MCP server"
  homepage "https://pretorin.com"
  version "0.24.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/pretorin-ai/homebrew-tap/releases/download/v0.24.2/pretorin-0.24.2-macos-arm64.tar.gz"
      sha256 "f63e3e7cd04bd5068101e895c756cdff8d5a45cbcbbbb0abae521cc54ff80f7f"
    end
    # No Intel macOS binary is built. Fail with a clear, actionable message at
    # formula-eval time instead of an opaque "undefined url" error.
    on_intel do
      odie "No Intel macOS binary. Install via: uv tool install pretorin (or pip/pipx install pretorin)."
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pretorin-ai/homebrew-tap/releases/download/v0.24.2/pretorin-0.24.2-linux-x86_64"
      sha256 "c5f7998de51a79617f391ca7813f44a1e435e6d4c3df95fe5a4b0e3042fdb5ce"
    end
    # No ARM Linux (aarch64) binary is built. Same clear-failure guard.
    on_arm do
      odie "No aarch64 Linux binary. Install via: uv tool install pretorin (or pip/pipx install pretorin)."
    end
  end

  def install
    if OS.mac?
      # macOS ships a PyInstaller *onedir* tar.gz: a single top-level
      # `pretorin/` dir holding the launcher and its `_internal/` payload. Brew
      # auto-extracts and descends into that dir, so the staged tree is the
      # launcher + `_internal/`. The two MUST stay co-located (PyInstaller loads
      # `_internal` relative to the exe), so install the whole tree into libexec
      # and expose just the launcher on PATH via a relative symlink.
      libexec.install Dir["*"]
      bin.install_symlink libexec/"pretorin"
    else
      # Linux ships a single, arch-named onefile executable (no archive). Install
      # the bare binary (reject any sidecar like .sha256/.spdx.json/.oci.tar should
      # one ever be co-staged) as the canonical command name `pretorin`.
      binary = Dir["pretorin-*"].grep_v(/\.(sha256|json|tar|sig|pub|asc)$/).first
      bin.install binary => "pretorin"
    end
  end

  def caveats
    <<~EOS
      MCP hosts (Claude, Cursor, Codex) reference the canonical path
        ~/.pretorin/bin/pretorin
      Point it at this Homebrew install with:
        pretorin link
      That command owns the canonical pin so the formula stays idiomatic and
      never writes to your home directory.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pretorin version")
  end
end
